---
title: "NEURAL NETWORK-GERMAN DATASET"
author: "Preethika P"
date: "12 November 2019"
output: html_document
---

#PACKAGES REQUIRED

```{r}
library(arules)
library(stats)
library(base)
library(h2o)
h2o.init() #start H2O on your local machine using all available cores

```

# import the Pima Indians Diabetes dataset; divide into train and test datasets

```{r}

file <- h2o.importFile(file.choose(),header=TRUE, sep=",")
file <- file[-c(1,6,7)]
splits <- h2o.splitFrame(file, 0.7, seed=33) #performing a 0.75: 0.25 split to form the train and test datasets
splits[[1]][,8]<- as.factor(splits[[1]][,8]) # 8 indicates your dependent variable convert it into factors,1 indicate train data split
splits[[2]][,8]<- as.factor(splits[[2]][,8]) # 2 indicate test split

```

#specify the parameters of the DL model

```{r}
dl1<-h2o.deeplearning(x=1:7, y="Risk",activation="Rectifier",training_frame = splits[[1]], hidden=c(150,150,150,150),epochs=10000 ) 

```

#generate predictions on the testset

```{r}
pred1=h2o.predict(dl1, newdata = splits[[2]])

```

#confusion matrix

```{r}
h2o.confusionMatrix(dl1, splits[[2]])

```


