---
title: "GERMAN CREDIT SALES ANALYSIS"
author: "Preethika P"
date: "2 November 2019"
output: html_document
---
##Load the load 
```{r}
german=read.csv(file.choose())
```



##The Variable saving a/c and Checking a/c has missing values and it is a categorical variable so it is supposed to be removed
```{r}
german=german[,-c(1,6:7)] ##deleting the s.no,saving a/c,checking a/c

```


##replace good and bad as 1 and 0 in Risk attribute
```{r}
library(plyr) ##used to replace the dependent variables as 0 and 1 from categorical variable
german$Risk<- revalue(german$Risk, c("good"=1))
german$Risk<- revalue(german$Risk, c("bad"=0))

```


##finding vif
```{r}

library(car) ##package is used for finding vif
model=glm(Risk~.,family=binomial(link='logit'),data=german)
vif(model)
summary(model)
german<-german[,-c(2,3)]  ##removed the categorical missing values
```


##creating train and test data
```{r}
set.seed(123)
dt = sort(sample(nrow(german), nrow(german)*.75))
train<-german[dt,]
test<-german[-dt,]
model1 <- glm(Risk ~.,family=binomial(link='logit'),data=train)
summary(model1)
```




##to predict 
```{r}
res1 <- predict(model1,newdata=subset(test,select=c(1,2,3,4,5)),type='response')
fitted.results <- ifelse(res1 > 0.5,1,0) ##thrushold-0.5,if it is greater than 0.5 then it is said to be 1 otherwise 0

```



##to find accuracy
```{r}
misClasificError <- mean(fitted.results != test$Risk)
print(paste('Accuracy',1-misClasificError))

```


##to find confusion matrix
```{r}
table(test$Risk, res1 > 0.5)
```







